# Generated by Django 3.2.6 on 2021-08-12 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_image_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
    ]
